// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231020231751_productosAniadidos")]
    partial class productosAniadidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Cantidad = 12,
                            Descripcion = "LO LOGRASTE, ESTOY ORGULLOSO",
                            Nombre = "NICO"
                        },
                        new
                        {
                            IdProducto = 2,
                            Cantidad = 1,
                            Descripcion = "Hola",
                            Nombre = "Sebas"
                        },
                        new
                        {
                            IdProducto = 5,
                            Cantidad = 22,
                            Descripcion = "Bai",
                            Nombre = "Rusky"
                        },
                        new
                        {
                            IdProducto = 3,
                            Cantidad = 4,
                            Descripcion = "Setso",
                            Nombre = "Tilin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
